services:
  db:
    image: postgres:17
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    environment:
      DATABASE_URL: postgres://postgres:mypassword@db:5432/postgres
    ports:
      - "5000:5000"
    depends_on:
      - db
  migrations:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: migrations
    restart: on-failure
    environment:
      DATABASE_URL: postgres://postgres:mypassword@db:5432/postgres
    command: ["npm", "run", "migrate"]
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_BASE_URL=http://localhost:5000/phones
    container_name: frontend
    restart: always
    ports:
      - "3001:80"
    depends_on:
      - backend
volumes:
  db_data:
